export { default as ContactUsPage } from './ContactUsPage/ContactUsPage'
export { default as FeesPage } from './FeesPage/FeesPage'
export { default as DealsPage } from './DealsPage/DealsPage'
export { default as FirstStepsPage } from './FirstStepsPage/FirstStepsPage'
export { default as FAQPage } from './FAQPage/FAQPage'
export { default as GuidebookForProvidersPage } from './GuidebookForProvidersPage/GuidebookForProvidersPage'
