import React from 'react';

export const termsAndConditionsContent = (
	<ol>
		<li>The Whichost Birthday Deal is currently available only for Ireland and the UK.</li>
		<li>You must have your Whichost account fully completed, especially the Birthday field.
			<ol>
				<li>Users with an incomplete profile and no Birthday date indicated, will not avail of this benefit.</li>
			</ol>
		</li>
		<li>You get a 100% refund as soon as the booking is confirmed, and not within five days of making use of the booking (having the celebration/party) as per the normal procedure.
			<ol>
				<li>The refund goes back to the same payment method used to request the booking;</li>
				<li>The refund might take between 7-15 business days. The speed depends entirely on the financial institution used by the user;</li>
				<li>This benefit is only valid for listings that are managed by Whichost.
					<ol>
						<li>You can find this information at the bottom of the description of the listing. If it`s managed by Whichost it will say: <b>This listing is managed by Whichost.</b></li>
					</ol>
				</li>
			</ol>

		</li>
		<li>By booking a pub over the Whichost platform, you get awarded a €5.00 or €10.00 Amazon Gift Card, plus €0.50 or €1.00 per additional person for parties of more than 10 people, for reviewing the pub on Whichost. Conditions:
			<ol>
				<li>€5.00 plus €0.50 per additional person (parties over 10 people), for parties that will be held on a Thursday, Friday, Saturday or Sunday.</li>
				<li>€10.00 plus €1.00 per additional person (parties over 10 people), for parties that will be held on a Monday, Tuesday or Wednesday.
				</li>
				<li>Only parties of 10 people or more will be considered for this benefit.
				</li>
				<li>Only the user that booked the pub can post the review.</li>
				<li>One review per booked party.</li>
				<li>The user must provide proof that the party was held. For this they can use Instagram, Facebook or Twitter as follows:
					<ol>
						<li>The user can prove that they held the party with an Instagram post:
							<ol>
								<li>The post must be generated by the same user that booked the party.</li>
								<li>The post must be a picture of the party being held at the pub, which means capturing as many of the party participants as possible at the pub.</li>
								<li>When posting the picture on Instagram, the user must properly tag the Whichost Instagram account by entering @whichost in the post. This will be the way for us to track.</li>
								<li>The post must be kept live on the user’s Instagram account for at least one full week (7 days).</li>
							</ol>
						</li>
						<li>The user can prove that they held the party with a Facebook post:
							<ol>
								<li>The post must be generated by the same user that booked the party.</li>
								<li>The post must contain a picture of the party being held at the pub, which means capturing as many of the party participants as possible at the pub.</li>
								<li>When posting the picture on Facebook, the user must properly tag the Whichost Facebook page by entering @whichost in the post and selecting the Whichost Facebook Page from the options that will be presented. For this to happen, the user must Like the Whichost Facebook Page previous to the post. This will be the way for us to track.</li>
								<li>The post must be kept live on the user’s Facebook account for at least one full week (7 days).</li>
							</ol>
						</li>
						<li>The user can prove that they held the party with a Twitter post:
							<ol>
								<li>The post must be generated by the same user that booked the party.</li>
								<li>The post must contain a picture of the party being held at the pub, which means capturing as many of the party participants as possible at the pub.</li>
								<li>When posting the picture on Twitter, the user must properly tag the Whichost Twitter account by entering @whichostie in the post. For this to happen, the user must follow the Whichost Twitter account previous to the post. This will be the way for us to track.</li>
								<li>The post must be kept live on the user’s Twitter account for at least one full week (7 days).</li>
							</ol>
						</li>
					</ol>
				</li>
				<li>The review must be submitted within one week of making use of the booking.</li>
				<li>All Amazon Gift Cards are sent electronically to the user’s email address in their Whichost account.</li>
				<li>The additional €0.50 or €1.00 reward per additional person is added to the value of the Amazon Gift Card.</li>
				<li>The maximum amount per Amazon Gift Card is €200.00.</li>
			</ol>	
		</li>
		<li>If the pub does not exist in the Whichost platform, you get awarded a €10.00 or €15.00 Amazon Gift Card, plus €0.50 or €1.00 per additional person for parties of more than 10 people, for recommending the pub, booking a party there through Whichost and posting a review. Conditions:
			<ol>
				<li>€10.00 plus €0.50 per additional person (parties over 10 people), for parties that will be held on a Thursday, Friday, Saturday or Sunday.</li>
				<li>€15.00 plus €1.00 per additional person (parties over 10 people), for parties that will be held on a Monday, Tuesday or Wednesday.</li>
				<li>Only parties of 10 people or more will be considered for this benefit.</li>
				<li>The user that recommended the pub must be the same one that books it through Whichost and celebrates their party there.</li>
				<li>The party must be booked at least one full week (7 days) after recommending the pub. That will give Whichost enough time to collect information on the pub and create the listing.</li>
				<li>Only the user that booked the pub can post the review.</li>
				<li>One review per booked party.</li>
				<li>The user must provide proof that the party was held. For this they can use Instagram, Facebook or Twitter as follows:
					<ol>
						<li>The user can prove that they held the party with an Instagram post:
							<ol>
								<li>The post must be generated by the same user that booked the party.</li>
								<li>The post must be a picture of the party being held at the pub, which means capturing as many of the party participants as possible at the pub.</li>
								<li>When posting the picture on Instagram, the user must properly tag the Whichost Instagram account by entering @whichost in the post. This will be the way for us to track.</li>
								<li>The post must be kept live on the user’s Instagram account for at least one full week (7 days).</li>
							</ol>
						</li>
						<li>The user can prove that they held the party with a Facebook post:
							<ol>
								<li>The post must be generated by the same user that booked the party.</li>
								<li>The post must contain a picture of the party being held at the pub, which means capturing as many of the party participants as possible at the pub.</li>
								<li>When posting the picture on Facebook, the user must properly tag the Whichost Facebook page by entering @whichost in the post and selecting the Whichost Facebook Page from the options that will be presented. For this to happen, the user must Like the Whichost Facebook Page previous to the post. This will be the way for us to track.</li>
								<li>The post must be kept live on the user’s Facebook account for at least one full week (7 days).</li>
							</ol>
						</li>
						<li>The user can prove that they held the party with a Twitter post:
							<ol>
								<li>The post must be generated by the same user that booked the party.</li>
								<li>The post must contain a picture of the party being held at the pub, which means capturing as many of the party participants as possible at the pub.</li>
								<li>When posting the picture on Twitter, the user must properly tag the Whichost Twitter account by entering @whichostie in the post. For this to happen, the user must follow the Whichost Twitter account previous to the post. This will be the way for us to track.</li>
								<li>The post must be kept live on the user’s Twitter account for at least one full week (7 days).</li>
							</ol>
						</li>
					</ol>
				</li>
				<li>The review must be submitted within one week of making use of the booking.
				</li>
				<li>All Amazon Gift Cards are sent electronically to the user’s email address in their Whichost account.</li>
				<li>The additional €0.50 or €1.00 reward per person is added to the value of the Amazon Gift Card.</li>
				<li>The maximum amount per Amazon Gift Card is €200.00.</li>
			</ol>
		</li>
		<li>All Amazon Gift Cards are provided in British Pound Sterling (‎£) and are valid for Amazon UK (www.amazon.co.uk).
			<ol>
				<li>At the day of issuing the Amazon Gift Card, we will convert your total award, from Euros (€) into British Pound Sterling (‎£) using the conversion rate provided by Google.</li>
			</ol>
		</li>
		<li>This Whichost benefit does not accumulate with any other deals, promotions or benefits that Whichost may provide at any time.</li>
		<li>Whichost users can avail this benefit only once per year.</li>
		<li>Whichost reserves the right to change these terms and conditions at any time without prior notice. In the event that any changes are made, the revised terms and conditions shall be published immediately.</li>
	</ol>	)
